services:
  react-app:
    build:
      context: ./react-app
      target: dev
    environment:
      - PUBLIC_URL=//localhost:8089/react1
      # - WDS_SOCKET_PORT=8089
    ports:
      - "3000:3000"
    networks:
      - app-network
  rails-app:
    build: https://${GH_TOKEN}@github.com/perfetti/rails-app.git
    image: rails
    ports:
      - 3000
    networks:
      - app-network
  react2-app:
    build: https://${GH_TOKEN}@github.com/perfetti/react2-app.git
    image: react2
    ports:
      - 3000
    networks:
      - app-network
  nginx:
    restart: always
    image: nginx:alpine
    ports:
      - 8089:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - rails-app
      - react-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
