version: "3.8"
services:
  node:
    build:
      context: ./api
      target: dev
    volumes:
      - ./api/index.js:/src/index.js
  nginx:
    restart: always
    image: nginx:alpine
    ports:
      - 8089:80
    volumes:
      - ./html5up-stellar/:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node
