version: "3.8"
services:
  node:
    build:
      context: ./api
      target: dev
    volumes:
      - ./api/index.js:/src/index.js
    networks:
      - app-network
  react-app:
    build:
      context: ./react-app
      target: dev
    environment:
      - PUBLIC_URL=//localhost:8089/react1
      # - WDS_SOCKET_PORT=8089
    ports:
      - "3000:3000"
    networks:
      - app-network
  nginx:
    restart: always
    image: nginx:alpine
    ports:
      - 8089:80
    volumes:
      - ./html5up-stellar/:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node
      - react-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
