services:
  frontend:
    build: ${FRONTEND_BUILD_CONTEXT}
    profiles: ["core", "test"]
    ports:
      - 3000
    networks:
      - app-network
    environment:
      - PUBLIC_URL=${FRONTEND_PUBLIC_URL}
      - WDS_SOCKET_PORT=${WDS_SOCKET_PORT}
  api:
    build: ${API_BUILD_CONTEXT}
    profiles: ["core", "test"]
    ports:
      - 3000
    networks:
      - app-network
    environment:
      - RAILS_HOST=${RAILS_HOST}
      - RAILS_RELATIVE_URL_ROOT=${RAILS_RELATIVE_URL_ROOT}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - RAILS_ENV=${RAILS_ENV}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    profiles: ["core", "test"]
    ports:
      - 5432
    networks:
      - app-network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 3
  backend:
    build: ${BACKEND_BUILD_CONTEXT}
    profiles: ["core", "test"]
    ports:
      - 3000
    environment:
      - PUBLIC_URL=${BACKEND_PUBLIC_URL}
      - WDS_SOCKET_PORT=${WDS_SOCKET_PORT}
    networks:
      - app-network
  nginx:
    image: nginx:alpine
    profiles: ["core", "test"]
    ports:
      - 8089:80
    volumes:
      - nginx_conf:/etc/nginx/conf.d
    depends_on:
      - api
      - frontend
      - backend
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://nginx:8089"]
      interval: 10s
      timeout: 5s
      retries: 3
  test:
    build: ./test
    profiles: ["test"]
    environment:
      - CYPRESS_BASE_URL=http://nginx:80
    networks:
      - app-network
    depends_on:
      - frontend
      - backend
      - api
      - db
      - nginx

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  nginx_conf:
