version: 2.1
orbs:
  cypress: cypress-io/cypress@3

workflows:
  test:
    jobs:
      - cypress/run:
          name: Run Cypress in Node 20
          cypress-command: npx wait-on@latest http://localhost:8089 && npx cypress run
          start-command: bash ./up_github.sh
          working-directory: test
          cypress-cache-key: >-
            cypress-cache-{{ arch }}-{{ checksum "libs/shared-ui/package.json"}}
