version: 2.1
orbs:
  cypress: cypress-io/cypress@3
jobs:
  run-services-then-cypress:
    executor:
      name: cypress/default
      node-version: "20.6"
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: ls -l $(ls)
      - run: bash ./build_github.sh
      - run: docker ps --format "table {{.Names}}\t{{.Ports}}" && docker compose ps
      - run: docker-compose up --build --no-deps -d test
      - run: docker compose exec test npx cypress run

workflows:
  test-harness:
    jobs:
      - run-cypress-in-specified-node-version:
          name: Run Cypress in Node 20
