version: 2.1
orbs:
  cypress: cypress-io/cypress@3
jobs:
  run-cypress-in-specified-node-version:
    executor:
      name: cypress/default
      node-version: "20.6"
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: ls -l $(ls)
      - run: bash ./build_github.sh
      - cypress/install:
          package-manager: npm
          working-directory: test
      - cypress/run-tests:
          cypress-command: npx wait-on@latest http://localhost:8089 && cd test && npx cypress run
          working-directory: test
workflows:
  use-my-orb:
    jobs:
      - run-cypress-in-specified-node-version:
          name: Run Cypress in Node 20
